version: "3"

volumes:
  kafka01-data: {}
  kafka02-data: {}
  kafka03-data: {}

### 
##  KAFKA_HOST_IP_ADDR - 主机 ip 地址
##  将变量写入 .env 文件，例如: KAFKA_HOST_IP_ADDR="172.16.2.32"
###

###
##  bootstrap-servers: ${KAFKA_HOST_IP_ADDR}:29091,${KAFKA_HOST_IP_ADDR}:29092,${KAFKA_HOST_IP_ADDR}:29093
##  访问 web UI http://${KAFKA_HOST_IP_ADDR}:18080
###

services:
  kafka01:
    image: sir5kong/kafka:v3.5
    # restart: always
    ports:
      - "29091:29091"
    volumes:
      - kafka01-data:/opt/kafka/data
    environment:
      - KAFKA_HEAP_OPTS=-Xmx512m -Xms512m
      - KAFKA_CLUSTER_ID=K7j2htIgTGiXLPDIjMiC9g
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CONTROLLER://:9091,PLAINTEXT://:9092,EXTERNAL://:29091
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092,EXTERNAL://${KAFKA_HOST_IP_ADDR}:29091
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka01:9091,2@kafka02:9091,3@kafka03:9091

  kafka02:
    image: sir5kong/kafka:v3.5
    # restart: always
    ports:
      - "29092:29092"
    volumes:
      - kafka02-data:/opt/kafka/data
    environment:
      - KAFKA_HEAP_OPTS=-Xmx512m -Xms512m
      - KAFKA_CLUSTER_ID=K7j2htIgTGiXLPDIjMiC9g
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CONTROLLER://:9091,PLAINTEXT://:9092,EXTERNAL://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092,EXTERNAL://${KAFKA_HOST_IP_ADDR}:29092
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka01:9091,2@kafka02:9091,3@kafka03:9091

  kafka03:
    image: sir5kong/kafka:v3.5
    # restart: always
    ports:
      - "29093:29093"
    volumes:
      - kafka03-data:/opt/kafka/data
    environment:
      - KAFKA_HEAP_OPTS=-Xmx512m -Xms512m
      - KAFKA_CLUSTER_ID=K7j2htIgTGiXLPDIjMiC9g
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CONTROLLER://:9091,PLAINTEXT://:9092,EXTERNAL://:29093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092,EXTERNAL://${KAFKA_HOST_IP_ADDR}:29093
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka01:9091,2@kafka02:9091,3@kafka03:9091

  ## Web UI for managing Kafka clusters (optional)
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.1
    # restart: always
    ports:
      - "18080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=sir5kong-demo
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka01:9092,kafka02:9092,kafka03:9092
      #- KAFKA_CLUSTERS_0_READONLY=true
